# Generated by Django 6.0.6 on 2026-06-12 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Rolo de tecido preto', max_length=150)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('MT', 'Metros'), ('RL', 'Rolo'), ('KG', 'Quilos'), ('CX', 'Caixa')], default='UN', max_length=2)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Alerta o patrão se baixar desse valor', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SAIDA', 'Saída (-)')], max_length=10)),
                ('quantidade_movimentada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, help_text='Ex: Tecido veio com defeito', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_movimentacoes', to='estoque.itemestoque')),
                ('usuario', models.ForeignKey(help_text='Quem fez a alteração no app', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Tecidos, Fios, Abas', max_length=100)),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='setores_permitidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemestoque',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.setor'),
        ),
    ]
