# Generated by Django 6.0.6 on 2026-06-27 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('cargo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GESTOR', 'Gestor'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=50)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='setor',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='setor',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='setores_gerenciados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GESTOR', 'Gestor'), ('OPERADOR', 'Operador'), ('GERENTE', 'Gerente')], default='OPERADOR', max_length=20),
        ),
    ]
