# Generated by Django 6.0.6 on 2026-06-16 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemestoque',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='estoque_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='quantidade_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.setor'),
        ),
        migrations.AlterField(
            model_name='itemestoque',
            name='unidade_medida',
            field=models.CharField(default='UN', max_length=10),
        ),
    ]
