# Generated by Django 6.0.6 on 2026-06-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_itemestoque_gerente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data_movimentacao']},
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade_movimentada',
            field=models.IntegerField(default=0),
        ),
    ]
